name: generate-and-publish

on:
  schedule:
    - cron: "0 6 * * *"   # Tous les jours à 06h00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Générer un article
        env:
          AMZN_TAG: ${{ secrets.AMZN_TAG }}
          AMZN_ASINS: ${{ secrets.AMZN_ASINS }}
          MODEL_ID: TinyLlama/TinyLlama-1.1B-Chat-v1.0
        run: |
          python generator.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto post $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "Aucun changement à publier."
          fi
